services:
  web:
    # CAMBIO IMPORTANTE: Usamos 'build' en vez de 'image'
    build: .       
    container_name: web-BM
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    # Ya no necesitamos el 'command' largo porque lo pusimos en el Dockerfile
    
  db:
    image: mariadb:11
    container_name: db-BM
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=app
      - MARIADB_USER=app
      - MARIADB_PASSWORD=app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pma-BM
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db_data: